# alerts.py
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import streamlit as st
import os


class AlertManager:

    @staticmethod
    def send_test_alert(recipient_email: str = None):
        """
        Send a test email alert.
        
        Args:
            recipient_email: Email to send to (optional, defaults to config)
        """
        try:
            # Get credentials from Streamlit secrets
            # ✅ CORRECT WAY: Access nested secrets with ["section"]["key"]
            smtp_server = st.secrets["email"]["smtp_server"]
            smtp_port = st.secrets["email"]["smtp_port"]
            smtp_email = st.secrets["email"]["smtp_email"]
            smtp_password = st.secrets["email"]["smtp_password"]
            
            # Use provided email or default from config
            if recipient_email is None:
                recipient_email = st.secrets["email"]["recipient_email"]
            
            # Email content
            subject = "🚨 Pharmacy Dashboard - Test Alert"
            
            body = f"""
Hello,

This is a TEST alert from your Pharmacy Inventory Dashboard.

If you received this email successfully:
✅ SMTP Configuration Works
✅ Email Notifications Are Active
✅ Alert System Is Functional

Test Details:
- Sent From: {smtp_email}
- Sent To: {recipient_email}
- Time: {st.session_state.get('current_time', 'N/A')}
- Dashboard: Pharmacy Inventory Monitoring System

---
This is an automated message. Do not reply.
Generated by Streamlit Dashboard
"""
            
            # Create email message
            msg = MIMEMultipart()
            msg["From"] = smtp_email
            msg["To"] = recipient_email
            msg["Subject"] = subject
            msg.attach(MIMEText(body, "plain"))
            
            # Send email via Gmail SMTP
            csv_content = "drug_id,drug_name,reorder_qty,manufacturer_name,manufacturer_phone\n"
            for _, drug in reorder_drugs_data.iterrows():
                csv_content += (
                    f"{drug.get('drug_id','')},{drug.get('drug_name','')},"
                    f"{drug.get('suggested_reorder_qty',0)},{drug.get('manufacturer_name','')},"
                    f"{drug.get('manufacturer_phone','')}\n"
                )

            attachment = MIMEBase('application', 'octet-stream')
            attachment.set_payload(csv_content.encode('utf-8'))
            encoders.encode_base64(attachment)
            attachment.add_header('Content-Disposition', 'attachment', filename='reorder_list.csv')
            msg.attach(attachment)

            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()  # Secure connection
                server.login(smtp_email, smtp_password)
                server.send_message(msg)
            
            return True
        
        except KeyError as e:
            raise Exception(f"Missing secret key: {str(e)}. Check your secrets.toml file.")
        
        except smtplib.SMTPAuthenticationError:
            raise Exception("❌ SMTP Authentication Failed. Check your email and password.")
        
        except smtplib.SMTPException as e:
            raise Exception(f"❌ SMTP Error: {str(e)}")
        
        except Exception as e:
            raise Exception(f"❌ Email Error: {str(e)}")

    @staticmethod
    def send_reorder_alert(reorder_drugs_data, recipient_email: str = None):
        """
        Send reorder alert with drug details.
        """
        try:
            smtp_server = st.secrets["email"]["smtp_server"]
            smtp_port = st.secrets["email"]["smtp_port"]
            smtp_email = st.secrets["email"]["smtp_email"]
            smtp_password = st.secrets["email"]["smtp_password"]
            
            if recipient_email is None:
                recipient_email = st.secrets["email"]["recipient_email"]
            
            subject = f"🔴 URGENT: {len(reorder_drugs_data)} Drugs Need Reorder TODAY"
            
            # Build drug list for email
            drugs_list = ""
            for _, drug in reorder_drugs_data.iterrows():
                drugs_list += f"""
Drug: {drug['drug_name']}
  - Current Stock: {drug['remaining_stock']} units
  - Reorder Point: {drug['reorder_point']} units
  - Suggested Qty: {drug['suggested_reorder_qty']} units
  - Manufacturer: {drug['manufacturer_name']}
  - Phone: {drug['manufacturer_phone']}
  - Lead Time: {drug['lead_time_days']} days
---
"""
            
            body = f"""
URGENT REORDER ALERT

The following {len(reorder_drugs_data)} drugs have reached their reorder point and need immediate restocking:

{drugs_list}

ACTION REQUIRED:
1. Review the list above
2. Contact manufacturer to place orders
3. Confirm receipt in pharmacy system
4. Update dashboard when stock arrives

Total Drugs Needing Reorder: {len(reorder_drugs_data)}

---
Sent by Pharmacy Inventory Dashboard
{st.session_state.get('current_time', 'N/A')}
"""
            
            msg = MIMEMultipart()
            msg["From"] = smtp_email
            msg["To"] = recipient_email
            msg["Subject"] = subject
            msg.attach(MIMEText(body, "plain"))
            
            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()
                server.login(smtp_email, smtp_password)
                server.send_message(msg)
            
            return True
        
        except Exception as e:
            raise Exception(f"Failed to send reorder alert: {str(e)}")